### PR TITLE
Added craft_items to machine definition for recipe creation

### PR DESCRIPTION
**Pull request by cyriax0**
There should be some recipes now to craft the machines. They are in the machine definition so the recipies have a consistent feel. They use groups to make them hopefully more portable.

### CODE REVIEW

**Review by wsor4035 — COMMENTED** [review]
this PR forces a hard dependency on default and is to hardcoded in its recipes

**Comment by wsor4035** [comment]
it would be much better to to rename craft_items to craft_reg or something and then direct pass that field of the def to minetest.register_craft `minetest.register_craft(def.craft_reg)`

**Review by S-S-X — APPROVED** [review]
> this PR forces a hard dependency on default and is to hardcoded in its recipes

In my opinion this does not really matter because that's already the case for mod before this addition.

More dynamic recipes should be added but should be separate thing from this PR, this is about adding usable recipe but not about fixing whole thing.

Not sure if adding `craft_items` to definition is good idea, might or might not be.
Probably wont be crazy big problem even if removed later but it is still part of public API.

For me recipe itself looks fine and I do believe that other things can be either changed later if absolutely needed (but for recipes most stuff is not really absolutely needed like ever) so approving this, recipes can also be adjusted if using groups causes any troubles later.

**Comment by S-S-X** [comment]
Option: register recipes in separate file without any magic, just static stuff and hardcoded items without any custom logic.

**Comment by wsor4035** [comment]
> In my opinion this does not really matter because that's already the case for mod before this addition.

this is entirely incorrect. https://github.com/mt-mods/home_workshop_modpack/blob/2058c587388b467fa490b1f2f70104b24f7b144c/home_workshop_misc/init.lua#L98-L101

**Comment by wsor4035** [comment]
additionally adding this in this fashion in a public api is terrible because we will be forced to support it as a matter of legacy compat in the future, so it should be properly fixed before being merged

**Comment by wsor4035** [comment]
superseeded by https://github.com/mt-mods/home_workshop_modpack/pull/6

**Comment by S-S-X** [comment]
> > In my opinion this does not really matter because that's already the case for mod before this addition.
> 
> this is entirely incorrect.
> 
> https://github.com/mt-mods/home_workshop_modpack/blob/2058c587388b467fa490b1f2f70104b24f7b144c/home_workshop_misc/init.lua#L98-L101

What I meant is that recipe registration does not require items to exist, you can remove `if minetest.get_modpath("default") and minetest.get_modpath("basic_materials") then` and it keeps working exactly same no matter if those mods are aavailable or not as long as it does not use any API provided by default or basic_materials.

**Comment by wsor4035** [comment]
> What I meant is that recipe registration does not require items to exist, you can remove `if minetest.get_modpath("default") and minetest.get_modpath("basic_materials") then` and it keeps working exactly same no matter if those mods are aavailable or not as long as it does not use any API provided by default or basic_materials.

The registration will work, but mods with crafting guides like unified inventory will show it as a unknown item which is bad ui/ux, so best to disable if it cant even be used anyways

**Comment by S-S-X** [comment]
> > What I meant is that recipe registration does not require items to exist, you can remove `if minetest.get_modpath("default") and minetest.get_modpath("basic_materials") then` and it keeps working exactly same no matter if those mods are aavailable or not as long as it does not use any API provided by default or basic_materials.
> 
> The registration will work, but mods with crafting guides like unified inventory will show it as a unknown item which is bad ui/ux, so best to disable if it cant even be used anyways

This is incorrect at least for unified inventory, not sure about other mods but if crafting items do not exist then it wont show up in unified inventory.
Unified inventory displays "no recipes" if only recipes with unavailable items were registered, same as no recipe at all.

**Pull request closed without merging**
